### ISSUE TITLE
An error occurs when using the software

### ISSUE THREAD

**Issue by zshu-alt** [Illumina/SMNCopyNumberCaller#11]
Hello! Now I have a complete bam file of the whole genome of a patient, but I made a mistake when using it. What is the problem? My bam file has bai file and I wrote absolute path, how can I solve this problem?? My code and log files are attached
And what does the --prefix parameter mean? Is it the name of the output file?
Your software is very important to me and I would appreciate it if you could solve my problem

[try.log](https://github.com/Illumina/SMNCopyNumberCaller/files/11469241/try.log)
[try.txt](https://github.com/Illumina/SMNCopyNumberCaller/files/11469242/try.txt)

**Comment by xiao-chen-xc** [comment]
Hi @zshu-alt, the manifest should be a text file listing the path to your bam files, one bam per line.

Yes the prefix is the name of the output file.

**Comment by zshu-alt** [comment]
Great my problem solved!! I misunderstood the parameter meaning, this is a simple error....
I would also like to ask, in order to get better results, what is the minimum amount of WGS samples needed? Is there a batch requirement?

**Comment by xiao-chen-xc** [comment]
A standard 30X or higher WGS coverage is recommended.
