### ISSUE TITLE
Error message when using cram file as input

### ISSUE THREAD

**Issue by melnel000** [Illumina/SMNCopyNumberCaller#3]
Hi

I am trying to run this program on a cram file and I am getting the following error message:

INFO:root:Processing sample FD01113665 at 2020-03-03 10:59:00.754390
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/a811b3dc9fe66af729dc0dddf7fa4f13": Protocol not supported
[E::cram_get_ref] Failed to populate reference for id 4
[E::cram_decode_slice] Unable to fetch reference #4 70044367..70079695
[E::cram_next_slice] Failure to decode slice

Please could you let me know what the problem might be.

Thanks!

**Comment by xiao-chen-xc** [comment]
Hi @melnel000, for a cram input, could you specify the reference fasta file with the --reference command so that the program can access the reference? Let me know if this does not solve the problem.

Thanks,
Xiao

**Comment by melnel000** [comment]
Thanks Xiao. I am able to run the program now.

Kind regards,
Melissa

Dr Melissa Nel (MBChB, PhD)
Neurology Research Group
Division of Neurology, E8-30, Groote Schuur Hospital
Department of Medicine, Faculty of Health Sciences
University of Cape Town
Observatory
Cape Town
7925
Tel: +27836438393
email: melnel000@gmail.com
