### ISSUE TITLE
Add SMNCopyNumberCaller to bioconda and nf-core.

### ISSUE THREAD

**Issue by peterpru** [Illumina/SMNCopyNumberCaller#7]
I would like to use this program as a recipe in bioconda, and as a nf-core module in nextflow.

I am currently adding these, and will update when it is complete.

**Comment by freconfarmer** [comment]
I am currently trying to learn how to use Anaconda and this program.  I have 3 cram files I want it to analyze. I've got as far as all requirements to run, but now trying to create a text file with the right information to run the program.

**Comment by peterpru** [comment]
> I am currently trying to learn how to use Anaconda and this program. I have 3 cram files I want it to analyze. I've got as far as all requirements to run, but now trying to create a text file with the right information to run the program.

Hi @freconfarmer, what do you mean? The input manifest.txt is a list of bam or cram files, where each row is a bam file. Is that your issue? Example below:
In _manifest.txt_:
`/path/to/file.cram`
`/path/to/file2.cram`

I am not the author of this program, so if you have specific issues, I recommend making a new issue or contacting the authors directly.

**Comment by peterpru** [comment]
Please find SMNcopynumbercaller on bioconda now: 
https://anaconda.org/bioconda/smncopynumbercaller

**Comment by freconfarmer** [comment]
Thanks for your reply. I’m a jack of all trades master of a very few things, not a programmer, and over my head in understanding code🤔 but I’m learning. I was using a win based anaconda, but realized I needed to install pysam-win which smncopynumbercaller won’t recognize, then switched over to Linux and another learning curve. You adding this to bioconda is awesome, I just need to figure out how to install everything on Linux.  But I’m a nubie at this.

**Comment by xiao-chen-xc** [comment]
Thanks so much for making this happen @peterpru !

**Comment by peterpru** [comment]
> Thanks so much for making this happen @peterpru !

No worries @xiao-chen-xc 😄 


> Thanks for your reply. I’m a jack of all trades master of a very few things, not a programmer, and over my head in understanding code🤔 but I’m learning. I was using a win based anaconda, but realized I needed to install pysam-win which smncopynumbercaller won’t recognize, then switched over to Linux and another learning curve. You adding this to bioconda is awesome, I just need to figure out how to install everything on Linux. But I’m a nubie at this.

No problems @freconfarmer , we all start somewhere, in a while you'll be an expert. For installing smncopynumbercaller to linux, you can install/set-up bioconda https://bioconda.github.io/index.html, and then do `conda install smncopynumbercaller`, and smncopynumber and its dependencies should then be installed.

**Comment by peterpru** [comment]
Bioconda: 
- https://bioconda.github.io/recipes/smncopynumbercaller/README.html#package-smncopynumbercaller
- conda install smncopynumbercaller

Singularity/docker containers:
- quay.io/biocontainers/smncopynumbercaller:1.1.2--py310h7cba7a3_0
- https://depot.galaxyproject.org/singularity/smncopynumbercaller:1.1.2--py310h7cba7a3_0

nf-core:
- https://nf-co.re/modules
- Installation command: nf-core modules install smncopynumbercaller

All done, closing issue.
